### ISSUE TITLE
Idea for plugin structure

### ISSUE THREAD

**Issue by mtoonen** [B3Partners/tailormap#1313]
A component (with javascript and java files) can be packaged in jar files:

- viewer points stripes to nl.b3p.viewer.stripes
  - plugin has a actionbean, defined in nl.b3p.viewer.stripes.<nameofplugin>
  - the actionbean maps the url to a normal/standard url: /action/<nameofplugin>
- plugin has some mechanism to subscribe itself (of flamingo requests all the subclasses of a predefined interface (ie. FlamingoPlugin), which has all the info for loading the plugin: javascript/java files)
- viewer reads the javascript files from the jarfiles via the ComponentResourceActionbean

This makes for easy separation of components, and for easier deployments with different components in it.

**Comment by mprins** [comment]
I think we may be able to get away with not registering in the java world, because if there is a backend then the will be a frontend that knows the url. The ViewerAdmin GUI is built using the components.json files, so I thing what you need is a way to "dynamically add components.json files to the context"

**Comment by mprins** [comment]
closing, no longer relevant due to upcoming architectural changes
